### ISSUE TITLE
Consider compiling DXVK-Sarek without the '-msse3' flag

### ISSUE THREAD

**Issue by WinterSnowfall** [pythonlover02/DXVK-Sarek#4]
Will probably leave some CPU-bound performance on the table, however this has the benefit of making DXVK-Sarek play nice with **any** x86-64 processor, even early P4s and the like.

I didn't want to include it part of my build-related PR, as I feel it's a choice you should weigh and make depending on how backwards-compatible you want DXVK-Sarek and Proton-Sarek to be, but it's definitely something worth considering IMHO.

**Comment by pythonlover02** [comment]
> Will probably leave some CPU-bound performance on the table, however this has the benefit of making DXVK-Sarek play nice with **any** x86-64 processor, even early P4s and the like.

That sounds nice, i will do some tests to see how much it affects and consider it.

> I didn't want to include it part of my build-related PR, as I feel it's a choice you should weigh and make depending on how backwards-compatible you want DXVK-Sarek and Proton-Sarek to be, but it's definitely something worth considering IMHO.

Thanks for this, i would have liked to have read this before doing the v1.10.5 release, but i guess that after the testing I will take the decision to include the change on v1.10.6 or not.

**Comment by pythonlover02** [comment]
About this, i have done some tests and to be honest i dont see it as worth it, not because i dont want to support very old CPUs, but because the bast majority of Proton/DXVK-Sarek users should have SSE3 capabilites, its sacrificing performance for a lot of people for a very very small number.
However, on this new release, i will add this as extra info + a tutorial of how to do it, so if anyone is using a CPU without SSE3 capabilities, they are free to compile it without it.

**Comment by WinterSnowfall** [comment]
Alright, I'll close this then.

> its sacrificing performance for a lot of people for a very very small number.

To be fair it's also sacrificing very very little performance most likely, but sure :P. On a sidenote, vkd3d-proton only targets SSE2 (so basically the x86-64 baseline), and I think Proton itself also does. But I agree people with SSE2 only CPUs these days should be a rarity. Even my "retro" Pentium 4-based Windows XP PC has SSE3 support, but technically there are some Athlon XP CPUs that lack it, IIRC.

> However, on this new release, i will add this as extra info + a tutorial of how to do it, so if anyone is using a CPU without SSE3 capabilities, they are free to compile it without it.

Sure, that sounds nice, though it's not exactly rocket science anyway :).

**Comment by pythonlover02** [comment]
> To be fair it's also sacrificing very very little performance most likely

Reopened this issue because i decided to redo the benchmarks. When i did them a few days ago, the performance loss wasn't big, but it wasn't small either. It went from 25,821 to 23,789 on the Resident Evil 6 benchmark tool. I ran the benchmarks about six times with each version.

I did the benchmarks again, and now the difference is basically nothing, going from 25760 with SSE3 to 25685 without it.

I've also got my test PC working again (an old office PC with an i5-2400, GT710 and 8GB of RAM). I did the test there too and it's the same there, almost no difference.

IDK why, but seeing as the difference isn't 8%, i'm rethinking my position.

**Comment by WinterSnowfall** [comment]
@pythonlover02 As a comment on the release notes:

> Note: This will make DXVK-Sarek run better on CPUs that do not support SSE3

Stuff compiled with SSE3 won't run at all on CPUs that don't support it. And that's true for any specific ISA extension/instruction set :wink:. So you've extended the list of CPUs dxvk-sarek can run on, actually.

**Comment by pythonlover02** [comment]
> @pythonlover02 As a comment on the release notes:
> 
> > Note: This will make DXVK-Sarek run better on CPUs that do not support SSE3
> 
> Stuff compiled with SSE3 won't run at all on CPUs that don't support it. And that's true for any specific ISA extension/instruction set 😉. So you've extended the list of CPUs dxvk-sarek can run on, actually.

OMW to fix it lol

**Comment by SoongVilda** [comment]
SSE3, Streaming SIMD Extensions 3, also known by its [Intel](https://en.wikipedia.org/wiki/Intel) code name Prescott New Instructions (PNI),[[1]](https://en.wikipedia.org/wiki/SSE3#cite_note-:1-1) is the third iteration of the [SSE](https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions) instruction set for the [IA-32](https://en.wikipedia.org/wiki/IA-32) (x86) architecture. Intel introduced SSE3 in early 2004 with the [Prescott](https://en.wikipedia.org/wiki/Pentium_4#Prescott) revision of their [Pentium 4](https://en.wikipedia.org/wiki/Pentium_4) CPU.[[1]](https://en.wikipedia.org/wiki/SSE3#cite_note-:1-1) In April 2005, [AMD](https://en.wikipedia.org/wiki/AMD) introduced a subset of SSE3 in revision E (Venice and San Diego) of their [Athlon 64](https://en.wikipedia.org/wiki/Athlon_64) CPUs.[[2]](https://en.wikipedia.org/wiki/SSE3#cite_note-2) The earlier [SIMD](https://en.wikipedia.org/wiki/SIMD) instruction sets on the [x86](https://en.wikipedia.org/wiki/X86) platform, from oldest to newest, are [MMX](https://en.wikipedia.org/wiki/MMX_(instruction_set)), [3DNow!](https://en.wikipedia.org/wiki/3DNow!) (developed by AMD, no longer supported on newer CPUs), [SSE](https://en.wikipedia.org/wiki/Streaming_SIMD_Extensions), and [SSE2](https://en.wikipedia.org/wiki/SSE2).

Source: https://en.wikipedia.org/wiki/SSE3

Are you sure turning it off is a good idea, on these old CPUs you would be lucky to get literally any performance bonus to keep any game running at a stable FPS. So I'm not sure turning off SSE3 was a good decision.

**Comment by WinterSnowfall** [comment]
> Are you sure turning it off is a good idea, on these old CPUs you would be lucky to get literally any performance bonus to keep any game running at a stable FPS. So I'm not sure turning off SSE3 was a good decision.

It's not about getting better performance on the affected CPUs, it's about being able to run the code at all. As I noted above, both Proton and vkd3d-proton target up to SSE2 both for x86 and x86-64 builds. The SSE3 instructions ultimately don't bring much benefit to dxvk and will ultimately have a negligible effect when CPU bound, and no effect whatsoever when GPU bound. Since dxvk-sarek is targeted at people using older hardware, it makes perfect sense.

**Comment by SoongVilda** [comment]
Okay, if you already performed text and there is no measurable difference, then that's fine.
